steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/drift-gateway:$BRANCH_NAME", "."]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/drift-gateway:$BRANCH_NAME"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "drift-gateway-$BRANCH_NAME"
      - "--image"
      - "gcr.io/$PROJECT_ID/drift-gateway:$BRANCH_NAME"
      - "--region"
      - "asia-southeast1"
      - "--set-secrets"
      - "DRIFT_GATEWAY_KEY=drift-gateway-key-sandbox:latest,RPC_ENDPOINT=drift-gateway-rpc-sandbox:latest"
      - "--set-env-vars"
      - "RUST_LOG=info"
      - "--vpc-connector"
      - "sipn-vpc-ase1"
      - "--vpc-egress"
      - "all-traffic"
      - "--no-cpu-throttling"
      - "--min-instances"
      - "1"
      - "--max-instances"
      - "1"
      - "--args=https://mainnet.helius-rpc.com/?api-key=8636d5f7-c957-4848-bea6-dbfa8602620e --host 0.0.0.0"
images:
  - "gcr.io/$PROJECT_ID/drift-gateway:$BRANCH_NAME"
options:
  logging: CLOUD_LOGGING_ONLY
